name: flutter_nearby_connections
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nankai.flutter_nearby_connections
        pluginClass: MainActivity
      ios:
        pluginClass: MainActivity